// Generated by apps/web/tools/build-pictograms.mjs from the pictograms listed there. Do not edit.

export const PICTOGRAM_SPRITE_VERSION = "6ce0e465ea";

export const PICTOGRAM_NAMES = [
  "backpack",
  "bell-ring",
  "binoculars",
  "bot",
  "brain-circuit",
  "calendar-sync",
  "chart-column",
  "chart-line",
  "code-xml",
  "cpu",
  "graduation-cap",
  "link-2",
  "palette",
  "party-popper",
  "repeat",
  "server",
  "shield",
  "square-kanban",
] as const;

export type PictogramName = (typeof PICTOGRAM_NAMES)[number];
